baseurl = "https://www.osgi.org/"
DefaultContentLanguage = "en"
title = "OSGi - The Dynamic Module System for Java"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The OSGi WG is a worldwide consortium of technology innovators that advances a proven and mature process to create open specifications that enable the modular assembly of software built with Java technology. Modularity reduces software complexity; OSGi is the best model to modularize Java."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse osgi", "osgi", "open source osgi", "dynamic module system", "java module"]
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
  logo = "images/logo/osgi.png"
  styles = "css/styles.css"
# favicon = ""
# share_img = ""
# header_wrapper_class = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
  featured_content_publish_target = "osgi"
#  call_for_action_text = "Download"
#  call_for_action_url = "//www.eclipse.org/downloads/"
#  call_for_action_icon = "fa-download"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1
  
[[menu.main]]
  name = "FAQ"
  parent = "About"
  url = "/about"
  weight = 1

[[menu.sidebar]]
  name = "About"
  url = "/about"
  weight = 2
  identifier = "about"
  
[[menu.sidebar]]
  parent ="about"
  name = "FAQ"
  url = "/about/faq"
  pre = "<i data-feather=\"help-circle\"></i>" # https://feathericons.com/
  weight = 1

[[menu.main]]
  name = "Members"
  url = "/membership"
  weight = 1

[[menu.sidebar]]
  name = "Members"
  url = "/membership/"
  weight = 2
  identifier = "membership"
  
[[menu.sidebar]]
  parent ="membership"
  name = "Membership Benefits"
  url = "/membership/#benefits"
  pre = "<i data-feather=\"award\"></i>"
  weight = 1

[[menu.sidebar]]
  parent ="membership"
  name = "Explore Our Members"
  url = "/membership/members/"
  pre = "<i data-feather=\"zap\"></i>"
  weight = 2
